# Generated by Django 3.2.3 on 2021-08-11 20:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
