# Generated by Django 3.2.3 on 2021-08-21 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210822_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='jobpost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.jobpost'),
        ),
    ]
