# Generated by Django 3.2.3 on 2021-07-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0004_profile_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAbout',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('about', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
    ]
