# Generated by Django 3.2.3 on 2021-08-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('ft', 'Full-time'), ('pt', 'Part-time'), ('con', 'Contract'), ('temp', 'Temporary'), ('vol', 'Volunteer'), ('int', 'Internship')], max_length=50),
        ),
    ]
