# Generated by Django 3.2.3 on 2021-09-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profileabout_profilepic'),
        ('home', '0007_alter_answer_question'),
    ]

    operations = [
    ]
