# Generated by Django 3.2.3 on 2021-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_jobpost_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='desc',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
